### ISSUE TITLE
无法使用了

### ISSUE THREAD

**Issue by tomwangcn** [IceyWu/RedBookSpider#1]
算法是更新了么

**Comment by IceyWu** [comment]
抱歉，使用的是发行版还是运行的源码，可以提供截图信息吗，我看一下

**Comment by tomwangcn** [comment]
abRequestId=cd3f56fd-622b-5eab-a696-6e0f8d25d939; webBuild=4.5.2; xsecappid=xhs-pc-web; a1=18e34ca6789acw6o0rbljpktp4k4j5bqpiqzsbp4q50000105005; webId=2d919b5ab9cf403e253c92ccd8146dec; gid=yYdq4S0KidUiyYdq4S0KW3DUYj0SEKl8FD1VA4AUT9U4Tu284V2DAM888y828828JDq2ji8W; web_session=040069b49b8bc146df85a69fc5374b86682b15; unread={%22ub%22:%2265d60beb000000000700674b%22%2C%22ue%22:%2265d42470000000000b018325%22%2C%22uc%22:17}; acw_tc=3947b5a3473601d4712e15836fe0d393d50e607bed845b1c0e4a64bf5eadc505; websectiga=8886be45f388a1ee7bf611a69f3e174cae48f1ea02c0f8ec3256031b8be9c7ee; sec_poison_id=19d48b1b-9adb-47e4-a181-7f4c1765a9e4




-----
这是cookie信息

**Comment by tomwangcn** [comment]
<img width="876" alt="image" src="https://github.com/IceyWu/RedBookSpider/assets/73059070/911c6862-e51e-48ef-9f3e-75911ece8e8f">

**Comment by IceyWu** [comment]
OK，感谢提供和指出，稍后我看看
